import type { Metadata } from "next";
import "./styles/globals.css";
import "./styles/fonts.css";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
  icons: {
    shortcut: "/assets/fav.png",
    icon: "/assets/fav.png",
    apple: "/assets/fav.png",
    other: {
      sizes: "any",
      url: "/assets/fav.png",
      rel: "apple-touch-icon",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased w-dvw overflow-x-hidden">{children}</body>
    </html>
  );
}
